#from https://github.com/GoogleCloudPlatform/cloud-builders-community -SB
## SB START - This file has to be modified:
# points to note:
# 1) TF version should be the one declared in here
# 2) Need to convert to use docker as gcloud will not run
# 3) Can it reach modulesf declared in the higher folders?
# 4) If yes, Modules can be versioned in separate folders and we can upgrade modules per tier.
# 5) replicate this in every project in every tier.
# 6) Understand the branching strategy and GitHub "codeowners" options
# 7) NOTE that in the backend.tf file, the state file has prefix = "env/dev/foso"

# I assume this can be done for every project in every tier thereby separating the state files
## SB END

steps:

# Add some checks around examples.

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Start"
    for d in environments/dev/; do
      readme="${d}README.md"
      if [[ ! -f "${readme}" ]]; then
        echo "${d}: ${readme} not found."
      fi
      config="${d}cloudbuild.yaml"
      if [[ ! -f "${config}" ]]; then
        echo "${d} failed: ${config} not found."
        continue

      else
        echo "${d} might succeed: ${config}  found."
        gcloud builds submit $d --config=${config}
        if [[ $? -ne 0 ]]; then
          echo "$d failed"
        else
          echo "$d passed"
        fi
      fi
    done
    echo "All builds succeeded."

#SB Need to see what this does? Does it tag the build

#tags: ['$_PR_NUMBER', '$_REPO_OWNER', '$_REPO', '$_SHA', 'cloud-builders-community']
